<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Minimart.com.vn - Siêu thị gia đình trực tuyến</title>
  <meta name="keywords" content="Rau sach, thuc pham sach, rau huu co, thuc pham huu co, thuc pham an toan, do uong, do gia dung, cham soc gia dinh, banh keo, bot giat, thit ca, thuc pham an lien, hoa my pham, do dien gia dung, do tre em, cham soc tre so sinh, khan giat, do kho, duo"/>
  <meta name="description" content="Minimart.com.vn - Siêu thị gia đình trực tuyến chuyên cung cấp thực phẩm sạch, sữa nhập khẩu, rau hữu cơ, thực phẩm hữu cơ, đồ dùng gia đình, thực phẩm an toàn, nước uống, chăm sóc sức khoẻ, chăm sóc gia đình , rượu bia, quà Tết, quà tặng trực tuyến, hoa, bánh kẹo, bột giặt, bột rửa chén bát, điện gia dụng, bánh kem, bình ủ sữa chua, máy xay cầm tay, hàng hiệu xách tay, nước hoa mỹ phẩm thời trang. Bán hàng trực tuyến, đảm bảo giá tốt nhất!"/>
  <link rel="canonical" href="http://minimart.com.vn/"/>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="RESOURCE-TYPE" content="DOCUMENT" />
  
  <link rel="stylesheet" href="../minimart/public/templates/default/script/bootstrap.min.css" type="text/css" />
  <link rel="stylesheet" href="../minimart/public/templates/default/script/style.css" type="text/css" />
</head>
<?php

if(isset($this->errorMessage))
{
	echo $this->errorMessage;
}
?>
<div class="container">
	<div class="row">
		
		<div class="col-lg-6 col-md-6 col-sm-6">
			<h1> <a href="http://localhost/minimart/public/"> <img style=" margin-top: -9px;" src="http://minimart.com.vn/template/default/images/homefinal.png" alt="" /> </a> »  Đăng nhập</h1>
			<div style="padding: 5px 0px 10px;" id="login_title"><b>Thông tin khách hàng đăng nhập hệ thống</b></div>
			<form role="form">
			  <div class="form-group">
			    <label for="exampleInputEmail1">Đại chỉ email *</label>
			    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" />
			  </div>
			  <div class="form-group">
			    <label for="exampleInputPassword1">Mật khẩu *</label>
			    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" />
			  </div>
			  <button type="submit" class="btn btn-warning">Đăng nhập</button>
			</form>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-6">
			<div style="padding: 54px 0px 10px;"><b>Bạn chưa là thành viên</b></div>
			 Đăng ký là thành viên để hưởng nhiều lợi ích và đặt mua hàng dễ dàng hơn.
			 <p><a style="color:#b00; font-weight: bold; text-decoration: none;" href="http://localhost/minimart/public/signup/" title="Click đăng ký tài khoản miễn phí">Đăng ký tài khoản</a></p>
		</div>
	</div>
</div>
</html>