<div id="top_right_menu">
	<span>Xin chào, </span>
	
	<a href="<?php echo $this->baseurl; ?>/login/">Đăng nhập</a> <span>|</span>
	<a href="<?php echo $this->baseurl; ?>/signup/">Đăng ký</a> <span>|</span> 
	
	<a href="<?php echo $this->baseurl; ?>/">Trang chủ</a> <span>|</span>
	<a href="/tin-khuyen-mai.html">Tin khuyến mãi</a> <span>|</span>
	<a href="/gioi-thieu">Giới thiệu</a> <span>|</span>
	<a href="/lien-he">Liên hệ</a>
</div>