<div class="tabs">
    <div id="ddtabs1" >
    <ul class="tab-links">
    <li class="active basictab"><a class='a_tab ' idvalue='#month-report'><?php echo $this->language['month'];echo $this->language['report'];?></a></li>
    <li class='basictab'><a class='a_tab ' idvalue='#working-paln'><?php echo $this->language['work'];echo $this->language['plan'];?></a></li>
    </ul>
    </div>
</div>
