<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Minimart.com.vn - Siêu thị gia đình trực tuyến</title>
  <meta charset="utf-8" />
  <meta name="keywords" content="Rau sach, thuc pham sach, rau huu co, thuc pham huu co, thuc pham an toan, do uong, do gia dung, cham soc gia dinh, banh keo, bot giat, thit ca, thuc pham an lien, hoa my pham, do dien gia dung, do tre em, cham soc tre so sinh, khan giat, do kho, duo"/>
  <meta name="description" content="Minimart.com.vn - Siêu thị gia đình trực tuyến chuyên cung cấp thực phẩm sạch, sữa nhập khẩu, rau hữu cơ, thực phẩm hữu cơ, đồ dùng gia đình, thực phẩm an toàn, nước uống, chăm sóc sức khoẻ, chăm sóc gia đình , rượu bia, quà Tết, quà tặng trực tuyến, hoa, bánh kẹo, bột giặt, bột rửa chén bát, điện gia dụng, bánh kem, bình ủ sữa chua, máy xay cầm tay, hàng hiệu xách tay, nước hoa mỹ phẩm thời trang. Bán hàng trực tuyến, đảm bảo giá tốt nhất!"/>
  <link rel="canonical" href="http://minimart.com.vn/"/>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta content="DOCUMENT" name="RESOURCE-TYPE" />
  
  <link rel="stylesheet" href="../../public/templates/default/script/bootstrap.min.css" type="text/css"/>
  <link rel="stylesheet" href="../../public/templates/default/script/style.css" type="text/css"/>
</head>
    <body>
        <?php echo $this->layout()->content;?>
    </body>
</html>