<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php
echo $this->render("_templates/header.phtml");
?>
<body>
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  ga('create', 'UA-52574934-1', 'auto');
  ga('send', 'pageview');
</script>
<div id="main">
  <div id="main_header">
    <div id="left_header">
      <div id="logo">
        <a href="/"><img src="/minimart/public/templates/default/images/logo_logo.png" alt="Minimart" /></a>
      </div>
    </div>
    <div id="right_header"> 
      <?php
      echo $this->render("_templates/menu.phtml");
      ?>
      <ul id="cs_header">
        <li><img src="/minimart/public/templates/default/images/lcpp.jpg" alt=""/></li>
        <li>
          <div id="transport_header">
            <img src="/minimart/public/templates/default/images/transport.png" alt="vận chuyển" class="bg_transport"/>
            <img src="/minimart/public/templates/default/images/content_transport.png" alt="" class="content_transport"/>
          </div>
        </li>
        <li><img src="/minimart/public/templates/default/images/ttknh.jpg" alt=""/></li>
      </ul>
      <div id="hotline_order">
        <span>04 66867668</span>
      </div>
    </div><!--right_header-->
    <div class="clr"></div>

    <div style="width:771px; float:right">
      <div id="main_search">
        <div id="fields">
          <div id="search_text"> Tìm kiếm</div>
          <form method="get" action="/tim" enctype="multipart/form-data">
            <?php
            echo $this->render("_templates/categories.phtml")
            ?>
            <div id="search_field" class="ui-widget">
              <input type="text" name="q" class="searchboxtext" placeholder="Gõ từ khóa tìm kiếm" />
            </div>
            <div id="search_button">
              <input type="submit" class="searchbutton" value="" />
            </div>
          </form>
          <div id="cart">
            <button class="cartButton" onclick="window.location='/gio-hang'">
              <span id="cart_number">Giỏ hàng (<span id="count_shopping_cart_store">0</span>)</span>
            </button>
          </div>
        </div>
      </div>
    </div><!--right-->
    <div class="clr"></div>
  </div><!--main_header-->
  <div class="clr"></div>


  <div id="main_container">
    <div id="left_container">
      <div id="ver_menu">
        <div id="header">
          <ul>
            <li id="mainmenu">
              <div class="mainli" style="background: transparent;">
                <a class="allstore" style="display: block;"></a>
              </div>
              <div class="mainDiv" id="menucontents" >
                <ul class="menu">

                  <li class="menuLink">
                    <div class="store"><a href="/thuc pham tuoi song.html">Thực phẩm tươi sống</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/thuy-hai-san.html">Thủy hải sản</a></li>

                          <li><a href="/ca.html">Cá</a></li>

                          <li><a href="/thit-bo.html">Thịt bò</a></li>

                          <li><a href="/thit-lon.html">Thịt lợn</a></li>

                          <li><a href="/thit-gia-cam.html">Thịt gia cầm</a></li>

                          <li><a href="/thuc-pham-dong-lanh.html">Thực phẩm đông lạnh</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/rau-cu-qua.html">Rau, củ, quả</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/Trai-cay.html">Trái cây</a></li>

                          <li><a href="/rau-cu.html">Rau củ</a></li>

                          <li><a href="/rau-gia-vi.html">Rau gia vị</a></li>

                          <li><a href="/nam.html">Nấm</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/do-dung-gia-dung.html">Đồ dùng gia dụng</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/do-dung-nha-bep.html">Đồ dùng nhà bếp</a></li>

                          <li><a href="/do-thuy-tinh-pha-le.html">Đồ thủy tinh, pha lê</a></li>

                          <li><a href="/do-su.html">Đồ sứ</a></li>

                          <li><a href="/binh-nuoc-khay-nhua.html">Bình nước, khay nhựa</a></li>

                          <li><a href="/phich-nuoc.html">Phích nước</a></li>

                          <li><a href="/hop-dung-thuc-an.html">Hộp đựng thực ăn</a></li>

                          <li><a href="/nylon-bao-quan-thuc-an.html">Nylon bảo quản thức ăn</a></li>

                          <li><a href="/pin-cac-loai.html">Pin các loại</a></li>

                          <li><a href="/san-pham-su-dung-1-lan.html">Sản phẩm sử dụng 1 lần</a></li>

                          <li><a href="/do-dung-khac.html">Đồ dùng khác</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/do uong banh-keo.html">Đồ uống, bánh kẹo</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/do-uong.html">Đồ uống</a></li>

                          <li><a href="/banh-keo-bim-bim.html">Bánh kẹo, Bim bim</a></li>

                          <li><a href="/san-pham-khac.html">Sản phẩm khác</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/thuc-pham-an-lien.html">Thực phẩm ăn liền</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/thuc pham che bien san.html">Thực phẩm chế biến sẵn</a></li>

                          <li><a href="/My-an-lien.html">Mỳ ăn liền</a></li>

                          <li><a href="/do-an-sang.html">Đồ ăn sáng</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/duong-sua-bot-ngu-coc.html">Đường, sữa, bột ngũ cốc</a>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/gia-vi-dau-an mam.html">Gia vị, dầu ăn, mắm</a>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/gao do-kho.html">Gạo, Đồ khô</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/gao.html">Gạo</a></li>

                          <li><a href="/ngu-coc.html">Ngũ Cốc</a></li>

                          <li><a href="/khac.html">Khác</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/do-dien-gia-dung.html">Đồ điện gia dụng</a>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/hoa-my-pham.html">Hóa mỹ phẩm</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/cham-soc-rang-mieng.html">Chăm sóc răng miệng</a></li>

                          <li><a href="/nuoc-rua-tay.html">Nước rửa tay</a></li>

                          <li><a href="/bot-giat-tay-xa-vai.html">Bột giặt, tẩy, xả vải</a></li>

                          <li><a href="/chat-tay-rua-khu-mui.html">Chất tẩy rửa, khử mùi</a></li>

                          <li><a href="/nuoc-rua-chen.html">Nước rửa chén</a></li>

                          <li><a href="/diet-con-trung.html">Diệt côn trùng</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/my-pham.html">Mỹ phẩm</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/san-pham-trang-diem.html">Sản phẩm trang điểm</a></li>

                          <li><a href="/san-pham-cham-soc-toc.html">Sản phẩm chăm sóc tóc</a></li>

                          <li><a href="/san-pham-cham-soc-da-.html">Sản phẩm chăm sóc da</a></li>

                          <li><a href="/lan-khu-mui-nuoc-hoa.html">Lăn khử mùi, nước hoa</a></li>

                          <li><a href="/bot-dao-cao-rau.html">Bọt, dao cạo râu</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/khan-giay.html">Khăn giấy</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/giay-an.html">Giấy ăn</a></li>

                          <li><a href="/giay-ve-sinh.html">Giấy vệ sinh</a></li>

                          <li><a href="/khan-giay-uot.html">Khăn giấy ướt</a></li>

                          <li><a href="/bvs-ta-giay-nguoi-lon.html">BVS, tã giấy người lớn</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/san-pham-may-mac.html">Sản phẩm may mặc</a>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/me va be.html">Mẹ và Bé</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/sua-bot.html">Sữa bột</a></li>

                          <li><a href="/bot-an-damtp-dduong.html">Bột ăn dặm,TP D.dưỡng</a></li>

                          <li><a href="/bim-cac-loai.html">Bỉm các loại</a></li>

                          <li><a href="/san-pham-cham-soc-be.html">Sản phẩm chăm sóc bé</a></li>

                          <li><a href="/do-choi.html">Đồ chơi</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/Hang-nhap-khau-duc-va-chau-au.html">Hàng nhập khẩu</a>

                      <div class="subMenu">
                        <ul> 

                          <li><a href="/hang-nhap-khau-uc.html">Hàng nhập khẩu Úc</a></li>

                          <li><a href="/hang-nhap-khau-han-quoc.html">Hàng nhập khẩu Hàn Quốc</a></li>

                          <li><a href="/hang-nhap-khau-duc.html">Hàng nhập khẩu Đức</a></li>

                        </ul>
                      </div>

                    </div>
                  </li> 

                  <li class="menuLink">
                    <div class="store"><a href="/thuc-an-cho-vat-nuoi.html">Thức ăn cho vật nuôi</a>

                    </div>
                  </li> 

                </ul>
              </div><!--mainDiv-->
            </li>
          </ul>
        </div>
        <div class="clr"></div>
      </div><!--ver_menu-->
      <div class="box_left" id="box_news_letter">
        <div class="title_box_left">
          <span>Đăng ký nhận bản tin</span>
        </div>
        <div class="content_box_left">
          <p class="summary_newsletter">Cảm ơn bạn đã quan tâm đến sản phẩm của chúng tôi, vui lòng điền điền thông tin của bạn để nhận bản tin khuyến mai sớm nhất</p>
          <div id="news_letter">
            <input type="text" id="name_newsletter" placeholder="Tên của bạn" />
            <input type="text" id="email_newsletter" placeholder="Email của bạn" />
            <a href="javascript:subscribe_newsletter()"><img src="/minimart/public/templates/default/images/send_newsletter.png" alt="" /></a>
          </div>
        </div>
      </div><!--box_left-->
      <div class="clr"></div>
      <div class="box_left" id="news_left">
        <div class="title_news"><a href="/tin-tuc"><img src="/minimart/public/templates/default/images/title_news_left.png" alt=""/></a></div>
        <div class="content_box_left list_news">
          <ul>


            <li>
              <a href="/Mach-ban-mot-so-cong-dung-cua-duong.html"><img src="/media/news/160_duong.jpg" alt="Mách bạn một số công dụng của đường" /></a>
              <a href="/Mach-ban-mot-so-cong-dung-cua-duong.html"><span class="name">Mách bạn một số công dụng của đường</span></a>
              <!--span class="summary">Đường có nhiều công dụng bên ngoài kệ bếp. Không chỉ giảm đau, làm nhiên ...</span-->
            </li>
            

            
            <li>
              <a href="/Meo-lam-thit-vit.html"><img src="/media/news/152_vitconguyenconlamsach.jpg" alt="Mẹo làm thịt vịt" /></a>
              <a href="/Meo-lam-thit-vit.html"><span class="name">Mẹo làm thịt vịt</span></a>
              <!--span class="summary">Làm thịt vịt luôn được coi là một việc không dễ của các bà nội trợ, vì ...</span-->
            </li>
            

            
            <li>
              <a href="/Bi-quyet-de-co-mon-ga-ran-gion-tan.html"><img src="/media/news/148_fci_ga_ran_gion.jpg" alt="Bí quyết để có món gà rán giòn tan" /></a>
              <a href="/Bi-quyet-de-co-mon-ga-ran-gion-tan.html"><span class="name">Bí quyết để có món gà rán giòn tan</span></a>
              <!--span class="summary">Cùng tham khảo những mẹo nhỏ dưới đây để có thể rán gà giòn da mà vẫn ...</span-->
            </li>
          </ul>
        </div><!--content_box_left-->
        <a href="/tin-tuc"><img src="/minimart/public/templates/default/images/more_news_left.png" alt="" /></a>
      </div><!--box_left-->
      <div class="box_left" id="congthuc">
        <div class="title_news"><a href="/cong-thuc-nau-an.html"><img src="/minimart/public/templates/default/images/title_congthuc_left.png" alt="" /></a></div>
        <div class="content_box_left list_news">
          <ul>


            <li>
              <a href="/Chim-cut-nuong-gion-ngon.html"><img src="/media/news/159_1361884966_anh.jpg" alt="Chim cút nướng giòn ngon" /></a>
              <a href="/Chim-cut-nuong-gion-ngon.html"><span class="name">Chim cút nướng giòn ngon</span></a>
              <!--span class="summary">Món chim cút nướng đảm bảo sẽ khiến cho cả gia đình cùng xuýt xoa thích thú.</span-->
            </li>
            

            
            <li>
              <a href="/Suon-kho-khoai-tay-dam-da-ngon-mieng.html"><img src="/media/news/158_suon_kho_khoai_tay_0a_75eae.jpg" alt="Sườn kho khoai tây đậm đà ngon miệng" /></a>
              <a href="/Suon-kho-khoai-tay-dam-da-ngon-mieng.html"><span class="name">Sườn kho khoai tây đậm đà ngon miệng</span></a>
              <!--span class="summary">Với vị ngon đậm đà cùng hương thơm đặc biệt từ lá lốt, hẳn món sườn kho ...</span-->
            </li>
            

            
            <li>
              <a href="/Tu-lam-o-mai-xao-gung.html"><img src="/media/news/157_coc_xao__10__ae948.jpg" alt="Tự làm ô mai cóc xào gừng " /></a>
              <a href="/Tu-lam-o-mai-xao-gung.html"><span class="name">Tự làm ô mai cóc xào gừng </span></a>
              <!--span class="summary">Ô mai cóc xào gừng hấp dẫn bởi vị chua ngọt hài hòa, thoảng hương gừng cay ...</span-->
            </li>
          </ul>
        </div><!--content_box_left-->
        <a href="/cong-thuc-nau-an.html"><img src="/minimart/public/templates/default/images/more_news_left.png" alt="" /></a>
      </div><!--box_left-->
    </div><!--left_container-->
    <div id="right_container">    
      <div id="slider">
        <div id="bigPic">

          <a href=""><img src="http://minimart.com.vn/media/banner/banner_c81e728d.png" alt="" /> </a>

          <a href=""><img src="http://minimart.com.vn/media/banner/banner_c4ca4238.png" alt="" /> </a>

          <a href=""><img src="http://minimart.com.vn/media/banner/banner_a87ff679.png" alt="" /> </a>

        </div>
        <ul id="thumbs">

          <li rel="1" class="active"></li>

          <li rel="2" ></li>

          <li rel="3" ></li>

        </ul> 
      </div><!--slider-->
      <div class="clr"></div>
      <div id="news_letter">
        <input type="text" id="email_newsletter" placeholder="Email của bạn" />
        <a href="javascript:subscribe_newsletter()"></a>
      </div>
      <div class="clr"></div>

      <div class="product_header">
        <h2 class="indexSubTitles">Mua nhiều</h2>
        <div class="moreBtn"><a href="/collection/mua-nhieu">Xem thêm »</a></div>
      </div>
      <div class="product_list">
        <ul>

          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4044" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/dau-phong-da-ca-vi-pho-mai-potachi-70gr-24gt.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4044_dau_phong_da_ca_vi_pho_mai_potachi_70gr_24gt.jpg" alt="Đậu phộng da cá vị phô mai Potachi 70gr (24G/T)" />

              </a>
              <a href="/dau-phong-da-ca-vi-pho-mai-potachi-70gr-24gt.html" class="p_name">Đậu phộng da cá vị phô mai Potachi 70gr (24G/T)</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','4044',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4041" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>



              <div class="price_off"><span>25%</span></div>

              <a href="/bman-afc-lua-mi-100g36ht.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4041_bman_afc_lua_mi_100g36ht.jpg" alt="B.Mặn AFC lúa mì 100G(36H/T)" />

              </a>
              <a href="/bman-afc-lua-mi-100g36ht.html" class="p_name">B.Mặn AFC lúa mì 100G(36H/T)</a>
              <div class="p_old_price">20.000 VNĐ</div>
              <div class="p_price">15.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','4041',1,'15000')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4042" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/dau-phong-da-ca-vi-thit-nuong-potachi-70gr-24gt.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4042_dau_phong_da_ca_vi_thit_nuong_potachi_70gr_24gt.jpg" alt="Đậu phộng da cá vị thịt nướng Potachi 70gr (24G/T)" />

              </a>
              <a href="/dau-phong-da-ca-vi-thit-nuong-potachi-70gr-24gt.html" class="p_name">Đậu phộng da cá vị thịt nướng Potachi 70gr (24G/T)</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','4042',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4043" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/dau-phong-da-ca-vi-thit-nuong-potachi-150gr-24gt.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4043_dau_phong_da_ca_vi_thit_nuong_potachi_150gr_24gt.jpg" alt="Đậu phộng da cá vị thịt nướng Potachi 150gr (24G/T)" />

              </a>
              <a href="/dau-phong-da-ca-vi-thit-nuong-potachi-150gr-24gt.html" class="p_name">Đậu phộng da cá vị thịt nướng Potachi 150gr (24G/T)</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','4043',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
        </ul>
      </div><!--product_list-->
      <div class="clr"></div>

      <div class="product_header">
        <h2 class="indexSubTitles">Thực phẩm sạch </h2>
        <div class="moreBtn"><a href="/collection/thuc-pham-sach">Xem thêm »</a></div>
      </div>
      <div class="product_list">
        <ul>

          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=11" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/xa-lachmoc-chau.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_11_xa_lachmoc_chau.jpg" alt="Xà lách*Mộc Châu" />

              </a>
              <a href="/xa-lachmoc-chau.html" class="p_name">Xà lách*Mộc Châu</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','11',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=19" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/nam-so-nau-tuoi-500gr.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_19_nam_so_nau_tuoi_500gr.jpg" alt="Nấm sò nâu tươi 500gr" />

              </a>
              <a href="/nam-so-nau-tuoi-500gr.html" class="p_name">Nấm sò nâu tươi 500gr</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','19',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=17" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/qua-su-su-da-lat.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_17_qua_su_su_moc_chau.jpg" alt="Quả su su Đà Lạt " />

              </a>
              <a href="/qua-su-su-da-lat.html" class="p_name">Quả su su Đà Lạt </a>
              <div class="p_old_price"></div>
              <div class="p_price">12.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','17',1,'12000')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=21" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/muop-huongmoc-chau.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_21_muop_huongmoc_chau.jpg" alt="Mướp hương*Mộc Châu" />

              </a>
              <a href="/muop-huongmoc-chau.html" class="p_name">Mướp hương*Mộc Châu</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','21',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
        </ul>
      </div><!--product_list-->
      <div class="clr"></div>

      <div class="product_header">
        <h2 class="indexSubTitles">Mẹ và bé</h2>
        <div class="moreBtn"><a href="/collection/me-va-be">Xem thêm »</a></div>
      </div>
      <div class="product_list">
        <ul>

          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4049" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/dau-mam-say-150gr-100gt.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4049_dau_mam_say_150gr_100gt.jpg" alt="Đậu mầm sấy 150gr (100G/T)" />

              </a>
              <a href="/dau-mam-say-150gr-100gt.html" class="p_name">Đậu mầm sấy 150gr (100G/T)</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','4049',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4045" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>



              <div class="price_off"><span>9%</span></div>

              <a href="/dau-phong-da-ca-vi-pho-mai-potachi-150gr-24gt.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4045_dau_phong_da_ca_vi_pho_mai_potachi_150gr_24gt.jpg" alt="Đậu phộng da cá vị phô mai Potachi 150gr (24G/T)" />

              </a>
              <a href="/dau-phong-da-ca-vi-pho-mai-potachi-150gr-24gt.html" class="p_name">Đậu phộng da cá vị phô mai Potachi 150gr (24G/T)</a>
              <div class="p_old_price">110.000 VNĐ</div>
              <div class="p_price">100.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','4045',1,'100000')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4041" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>



              <div class="price_off"><span>25%</span></div>

              <a href="/bman-afc-lua-mi-100g36ht.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4041_bman_afc_lua_mi_100g36ht.jpg" alt="B.Mặn AFC lúa mì 100G(36H/T)" />

              </a>
              <a href="/bman-afc-lua-mi-100g36ht.html" class="p_name">B.Mặn AFC lúa mì 100G(36H/T)</a>
              <div class="p_old_price">20.000 VNĐ</div>
              <div class="p_price">15.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','4041',1,'15000')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4046" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>



              <div class="price_off"><span>55%</span></div>

              <a href="/dau-phong-da-ca-nutz-vi-nuoc-cot-dua-32gr-120gt.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4046_dau_phong_da_ca_nutz_vi_nuoc_cot_dua_32gr_120gt.jpg" alt="Đậu phộng da cá Nutz vị nước cốt dừa 32gr (120G/T)" />

              </a>
              <a href="/dau-phong-da-ca-nutz-vi-nuoc-cot-dua-32gr-120gt.html" class="p_name">Đậu phộng da cá Nutz vị nước cốt dừa 32gr (120G/T)</a>
              <div class="p_old_price">4.400 VNĐ</div>
              <div class="p_price">2.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','4046',1,'2000')" class="p_btn_buy"></a>
            </div>
          </li>
          
        </ul>
      </div><!--product_list-->
      <div class="clr"></div>

      <div class="product_header">
        <h2 class="indexSubTitles">Hàng nhập khẩu</h2>
        <div class="moreBtn"><a href="/collection/hang-nhap-khau">Xem thêm »</a></div>
      </div>
      <div class="product_list">
        <ul>

          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4057" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/kem-sorbolene-250g.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4057_15101003.jpg" alt="Kem Sorbolene 250g" />

              </a>
              <a href="/kem-sorbolene-250g.html" class="p_name">Kem Sorbolene 250g</a>
              <div class="p_old_price"></div>
              <div class="p_price">285.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','4057',1,'285000')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=4055" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/Kem-cuu-dem.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_4055_k1501101.jpg" alt="Kem cừu đêm" />

              </a>
              <a href="/Kem-cuu-dem.html" class="p_name">Kem cừu đêm</a>
              <div class="p_old_price"></div>
              <div class="p_price">308.000 VNĐ</div>
              <a href="javascript:addToShoppingCart('pro','4055',1,'308000')" class="p_btn_buy"></a>
            </div>
          </li>
          
        </ul>
      </div><!--product_list-->
      <div class="clr"></div>

      <div class="product_header">
        <h2 class="indexSubTitles">Đồ gia dụng</h2>
        <div class="moreBtn"><a href="/collection/do-gia-dung">Xem thêm »</a></div>
      </div>
      <div class="product_list">
        <ul>

          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=2260" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/bo-gia-vi-doi-630.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_2260_bo_gia_vi_doi_630.jpg" alt="Bộ gia vị đôi 630" />

              </a>
              <a href="/bo-gia-vi-doi-630.html" class="p_name">Bộ gia vị đôi 630</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','2260',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=1754" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/tui-giat-do-0100.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_1754_tui_giat_do_0100.jpg" alt="Túi giặt đồ 0100" />

              </a>
              <a href="/tui-giat-do-0100.html" class="p_name">Túi giặt đồ 0100</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','1754',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=2193" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/gio-dung-hu-gia-vi-co-tay-cam-hy2608.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_2193_gio_dung_hu_gia_vi_co_tay_cam_hy2608.jpg" alt="Giỏ đựng hũ gia vị có tay cầm HY2608" />

              </a>
              <a href="/gio-dung-hu-gia-vi-co-tay-cam-hy2608.html" class="p_name">Giỏ đựng hũ gia vị có tay cầm HY2608</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','2193',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
          <li>
            <div class="p_container">
              <a href="/ajax/product_detail.php?productId=2192" class="xemnhanh fancybox fancybox.ajax"><img alt="Xem nhanh" class="btnQuickView" src="/minimart/public/templates/default/images/blank.gif" /></a>

              <a href="/gia-treo-dung-cu-nha-bep-hy2576.html" class="p_img">

                <img src="/minimart/public/templates/default/images/250_2192_gia_treo_dung_cu_nha_bep_hy2576.jpg" alt="Giá treo dụng cụ nhà bếp HY2576" />

              </a>
              <a href="/gia-treo-dung-cu-nha-bep-hy2576.html" class="p_name">Giá treo dụng cụ nhà bếp HY2576</a>
              <div class="p_old_price"></div>
              <div class="p_price">Liên hệ</div>
              <a href="javascript:addToShoppingCart('pro','2192',1,'0')" class="p_btn_buy"></a>
            </div>
          </li>
          
        </ul>
      </div><!--product_list-->
      <div class="clr"></div>

    </div><!--right_container-->
  </div><!--main_container-->
  <div class="clr"></div>

  <!--
  include footer
  //begin
-->
<?php
echo $this->render("_templates/footer.phtml")
?>
  <!--
  //end
-->
<div class="clr"></div>
<script> 

  function subscribe_newsletter(){
    var email = document.getElementById('email_newsletter').value;
    if(email.length > 3){
      $.post("/ajax/register_for_newsletter.php", {email:email}, function(data) {
        if(data=='success') {alert("Quý khách đã đăng ký thành công "); }
        else if(data=='exist'){ alert("Email này đã tồn tại");}
        else { alert('Lỗi xảy ra, vui lòng thử lại '); }

      });
    }else{alert('Vui lòng nhập địa chỉ email');}
  }

  $(document).ready(function(){
    $(".close_letter").click(function(){
      $("#news_letter_fix").fadeOut();
      return false;
    });
    $("#icon_mail_fix").click(function(){
      $("#news_letter_fix").fadeIn();
    });
  });
</script>

<!--div id="icon_mail_fix"></div>
<div id="news_letter_fix">
  <a href="" class="close_letter"></a>
  <p>Vui lòng điền điền thông tin email của bạn để nhận bản tin khuyến mãi sớm nhất</p>
  <input type="text" id="email_newsletter" placeholder="Email của bạn" />
  <a href="javascript:subscribe_newsletter()">Đăng ký</a>
</div-->

</div>
</body>
</html>
<!-- Load time: 0.28 seconds-->
<!-- Powered by HuraStore 5.0 / Website: www.HuraSoft.vn -->  
