<?php
echo $this->render("_templates/header.phtml");
?>
<body>
  <script language="JavaScript">
    var i = 0;
    var path = new Array();

    // LIST OF IMAGES
    path[0] = "http://minimart.com.vn/media/banner/banner_c81e728d.png";
    path[1] = "http://minimart.com.vn/media/banner/banner_c4ca4238.png";
    path[2] = "http://minimart.com.vn/media/banner/banner_a87ff679.png";

    function swapImage()
    {
      document.slide.src = path[i];
      if(i < path.length - 1) i++; else i = 0;
      setTimeout("swapImage()",3000);
    }
    window.onload=swapImage;
  </script>

<div id="main">
  <div id="main_header">
    <div id="left_header">
      <div id="logo">
        <a href="<?php echo $this->baseurl;?>"><img src="/minimart/public/templates/default/images/logo_logo.png" alt="Minimart" /></a>
      </div>
    </div>
    <div id="right_header"> 
      <?php
      echo $this->render("_templates/menu.phtml");
      ?>
      <ul id="cs_header">
        <li><img src="/minimart/public/templates/default/images/lcpp.jpg" alt=""/></li>
        <li>
          <div id="transport_header">
            <img src="/minimart/public/templates/default/images/transport.png" alt="vận chuyển" class="bg_transport"/>
            <img src="/minimart/public/templates/default/images/content_transport.png" alt="" class="content_transport"/>
          </div>
        </li>
        <li><img src="/minimart/public/templates/default/images/ttknh.jpg" alt=""/></li>
      </ul>
      <div id="hotline_order">
        <span>04 66867668</span>
      </div>
    </div><!--right_header-->
    <div class="clr"></div>

    <div style="width:771px; float:right">
      <div id="main_search">
        <div id="fields">
          <div id="search_text"> Tìm kiếm</div>
          <form method="get" action="/tim" enctype="multipart/form-data">
            <?php
            echo $this->render("_templates/categories.phtml")
            ?>
            <div id="search_field" class="ui-widget">
              <input type="text" name="q" class="searchboxtext" placeholder="Gõ từ khóa tìm kiếm" />
            </div>
            <div id="search_button">
              <input type="submit" class="searchbutton" value="" />
            </div>
          </form>
          <div id="cart">
            <button class="cartButton" onclick="window.location='/gio-hang'">
              <span id="cart_number">Giỏ hàng (<span id="count_shopping_cart_store">0</span>)</span>
            </button>
          </div>
        </div>
      </div>
    </div><!--right-->
    <div class="clr"></div>
  </div><!--main_header-->
  <div class="clr"></div>


  <div id="main_container">
    <div id="left_container">
      <div id="ver_menu">
        <div id="header">
          <ul>
            <li id="mainmenu">
              <div class="mainli" style="background: transparent;">
                <a class="allstore" style="display: block;"></a>
              </div>
              <div class="mainDiv" id="menucontents">
                <ul class="menu">

                <?php foreach ($this->data_category as $key => $value){ ?>

                    <li class="menuLink">
                      <div class="store"><a href="#"><?php echo $value['category_name'];?></a>
                      <div class="subMenu">
                        <ul>

                          <?php $data_product_type = $this->model_->execQuery('CALL GET_PRODUC_TYPE_BY_CATEGORY_ID('.$value['category_id'].')'); 
                          foreach ($data_product_type as $key => $value_) { ?>

                          <li><a href="#"><?php echo $value_['name'];?></a></li>

                          <?php } ?>
                        </ul>
                      </div>
                      </div>
                    </li>

                  <?php } ?>
                </ul>
              </div><!--mainDiv-->
            </li>
          </ul>
        </div>
        <div class="clr"></div>
      </div><!--ver_menu-->
      <div class="box_left" id="box_news_letter">
        <div class="title_box_left">
          <span>Đăng ký nhận bản tin</span>
        </div>
        <div class="content_box_left">
          <p class="summary_newsletter">Cảm ơn bạn đã quan tâm đến sản phẩm của chúng tôi, vui lòng điền điền thông tin của bạn để nhận bản tin khuyến mai sớm nhất</p>
          <div id="news_letter">
            <input type="text" id="name_newsletter" placeholder="Tên của bạn" />
            <input type="text" id="email_newsletter" placeholder="Email của bạn" />
            <a href="javascript:subscribe_newsletter()"><img src="/minimart/public/templates/default/images/send_newsletter.png" alt="" /></a>
          </div>
        </div>
      </div><!--box_left-->
      <div class="clr"></div>
      <div class="box_left" id="news_left">
        <div class="title_news"><a href="/tin-tuc"><img src="/minimart/public/templates/default/images/title_news_left.png" alt=""/></a></div>
        <div class="content_box_left list_news">
          <ul>


            <li>
              <a href="/Mach-ban-mot-so-cong-dung-cua-duong.html"><img src="/media/news/160_duong.jpg" alt="Mách bạn một số công dụng của đường" /></a>
              <a href="/Mach-ban-mot-so-cong-dung-cua-duong.html"><span class="name">Mách bạn một số công dụng của đường</span></a>
              <!--span class="summary">Đường có nhiều công dụng bên ngoài kệ bếp. Không chỉ giảm đau, làm nhiên ...</span-->
            </li>
            

            
            <li>
              <a href="/Meo-lam-thit-vit.html"><img src="/media/news/152_vitconguyenconlamsach.jpg" alt="Mẹo làm thịt vịt" /></a>
              <a href="/Meo-lam-thit-vit.html"><span class="name">Mẹo làm thịt vịt</span></a>
              <!--span class="summary">Làm thịt vịt luôn được coi là một việc không dễ của các bà nội trợ, vì ...</span-->
            </li>
            

            
            <li>
              <a href="/Bi-quyet-de-co-mon-ga-ran-gion-tan.html"><img src="/media/news/148_fci_ga_ran_gion.jpg" alt="Bí quyết để có món gà rán giòn tan" /></a>
              <a href="/Bi-quyet-de-co-mon-ga-ran-gion-tan.html"><span class="name">Bí quyết để có món gà rán giòn tan</span></a>
              <!--span class="summary">Cùng tham khảo những mẹo nhỏ dưới đây để có thể rán gà giòn da mà vẫn ...</span-->
            </li>
          </ul>
        </div><!--content_box_left-->
        <a href="/tin-tuc"><img src="/minimart/public/templates/default/images/more_news_left.png" alt="" /></a>
      </div><!--box_left-->
      <div class="box_left" id="congthuc">
        <div class="title_news"><a href="/cong-thuc-nau-an.html"><img src="/minimart/public/templates/default/images/title_congthuc_left.png" alt="" /></a></div>
        <div class="content_box_left list_news">
          <ul>


            <li>
              <a href="/Chim-cut-nuong-gion-ngon.html"><img src="/media/news/159_1361884966_anh.jpg" alt="Chim cút nướng giòn ngon" /></a>
              <a href="/Chim-cut-nuong-gion-ngon.html"><span class="name">Chim cút nướng giòn ngon</span></a>
              <!--span class="summary">Món chim cút nướng đảm bảo sẽ khiến cho cả gia đình cùng xuýt xoa thích thú.</span-->
            </li>
            

            
            <li>
              <a href="/Suon-kho-khoai-tay-dam-da-ngon-mieng.html"><img src="/media/news/158_suon_kho_khoai_tay_0a_75eae.jpg" alt="Sườn kho khoai tây đậm đà ngon miệng" /></a>
              <a href="/Suon-kho-khoai-tay-dam-da-ngon-mieng.html"><span class="name">Sườn kho khoai tây đậm đà ngon miệng</span></a>
              <!--span class="summary">Với vị ngon đậm đà cùng hương thơm đặc biệt từ lá lốt, hẳn món sườn kho ...</span-->
            </li>
            

            
            <li>
              <a href="/Tu-lam-o-mai-xao-gung.html"><img src="/media/news/157_coc_xao__10__ae948.jpg" alt="Tự làm ô mai cóc xào gừng " /></a>
              <a href="/Tu-lam-o-mai-xao-gung.html"><span class="name">Tự làm ô mai cóc xào gừng </span></a>
              <!--span class="summary">Ô mai cóc xào gừng hấp dẫn bởi vị chua ngọt hài hòa, thoảng hương gừng cay ...</span-->
            </li>
          </ul>
        </div><!--content_box_left-->
        <a href="/cong-thuc-nau-an.html"><img src="/minimart/public/templates/default/images/more_news_left.png" alt="" /></a>
      </div><!--box_left-->
    </div><!--left_container-->
    <div id="right_container"> 
    </div><!--right_container-->
  </div><!--main_container-->
  <div class="clr"></div>

  <!--
  include footer
  //begin
-->
<?php
echo $this->render("_templates/footer.phtml")
?>
  <!--
  //end
-->
<div class="clr"></div>
<script> 

  function subscribe_newsletter(){
    var email = document.getElementById('email_newsletter').value;
    if(email.length > 3){
      $.post("/ajax/register_for_newsletter.php", {email:email}, function(data) {
        if(data=='success') {alert("Quý khách đã đăng ký thành công "); }
        else if(data=='exist'){ alert("Email này đã tồn tại");}
        else { alert('Lỗi xảy ra, vui lòng thử lại '); }

      });
    }else{alert('Vui lòng nhập địa chỉ email');}
  }

  $(document).ready(function(){
    $(".close_letter").click(function(){
      $("#news_letter_fix").fadeOut();
      return false;
    });
    $("#icon_mail_fix").click(function(){
      $("#news_letter_fix").fadeIn();
    });
  });
</script>

</div>
</body>
</html>
<!-- Load time: 0.28 seconds-->
<!-- Powered by HuraStore 5.0 / Website: www.HuraSoft.vn -->  
