<?php
if(isset($this->errorMessage)){
	echo $this->errorMessage;
}
?>
<div class="container">
<div class="row">
<div id="location">
	<a href=""><img style="float: left;margin-right: 5px;" src="http://minimart.com.vn/template/default/images/homefinal.png" alt="" /></a> <span style="display: inline;">»</span> <h1 style="display: inline;">Sign up</h1>
</div>
</div>
<div class="clr"></div>
<div class="col-lg-12 col-md-12 col-sm-6">
<div class="form-group">
<?php
	echo $this->form;	
?>
</div>
</div>
</div>