<html>
<head>
    <meta http-equiv="content-type" content="text/html" />
    <meta charset="uft-8"/>
	<?php 
		echo $this->headLink ();
		echo $this->headscript ();
	?>
	<title>User Management</title>
</head>


<body>
<div class='admin_main'>
	<div class='heading'>
		<h1>User Management</h1>
	</div>
	<?php echo $this->render('_templates/tab_top.phtml');?>
	<div class='admin_content'>
		<div class='button_layout'>
			<input type="text" class="search square" name='searchquery' value='' maxlength="88" placeholder='User Id ,Name'>
			<input type='button' class='buttonH' value='Search'>	
			<input id='save' class='buttonH' type="button" value="Save" style="float: right;" >
			<input class='buttonH' type="button" value="Delete Row" style="float: right;">
			<input class='buttonH' type="button" value="Add Row"  style="float: right;">
			<a href="usermanagement"><input class='buttonH' type="button" value="Reset" style="float: right;"></a>	
		</div>
		<div class='admin_content_table'>
		<table class='admin_table'>
			<tr>
				<th width='32px'>
					<input type='checkbox' name="list" id='cb' class="css-checkbox" />
				</th>
				<th width='8%'><?php echo 'User Id'; ?></th>
				<th width='10%'><?php echo 'Password'; ?></th>
				<th width=''><?php echo 'User Name'; ?></th>
				<th width='10%'><?php echo 'Phone'; ?></th>
				<th width='16%'><?php echo 'Email'; ?></th>
				<th width='100px'><?php echo 'Address'; ?></th>
				<th width='100px'><?php echo 'Money'; ?></th>
				<th width='13%'><?php echo 'Sigup time'; ?></th>
				<th width='10%'><?php echo 'Status'; ?></th>
			</tr>	
			<?php 
			if(count($this->listUser)!=0){
				foreach($this->listUser as $userInfor){?>
					<tr>
				<td width='32px'>
					<input type='checkbox' name="list" id='cb' class="css-checkbox" />
				</td>
				<td width='8%'> <?php echo $userInfor['user_id']; ?></td>
				<td width='10%'><?php echo $userInfor['password']; ?></td>
				<td width=''><?php echo 'User Name'; ?></td>
				<td width='10%'><?php echo $userInfor['phone']; ?></td>
				<td width='16%'><?php echo $userInfor['email']; ?></td>
				<td width='100px'><?php echo $userInfor['address']; ?></td>
				<td width='100px'><?php echo $userInfor['money']; ?></td>
				<td width='13%'><?php echo $userInfor['sigup_time']; ?></td>
				<td width='10%'><?php echo $userInfor['status']; ?></th>
			</tr>
			<?php 	
				}	
			}
			?>				
		</table>
		</div>
	</div>
</div>
</body>
</html>