<div id="dropdown">
    <select name="scat_id" id="jumpMenu">
        <option>Tất cả danh mục</option>

        <option value="20">Thực phẩm tươi sống</option>

        <option value="19">Rau, củ, quả</option>

        <option value="27">Đồ dùng gia dụng</option>

        <option value="22">Đồ uống, bánh kẹo</option>

        <option value="21">Thực phẩm ăn liền</option>

        <option value="42">Đường, sữa, bột ngũ cốc</option>

        <option value="38">Gia vị, dầu ăn, mắm</option>

        <option value="37">Gạo, Đồ khô</option>

        <option value="28">Đồ điện gia dụng</option>

        <option value="25">Hóa mỹ phẩm</option>

        <option value="26">Mỹ phẩm</option>

        <option value="30">Khăn giấy</option>

        <option value="31">Sản phẩm may mặc</option>

        <option value="29">Mẹ và Bé</option>

        <option value="32">Hàng nhập khẩu</option>

        <option value="45">Thức ăn cho vật nuôi</option>
    </select>
</div>