<div id="copyright"><span>&copy; 2014 Minimart.com.vn - Siêu thị gia đình trực tuyến!</span></div>
<div id="footer">
  <div class="box_footer" id="address_footer">
    <h3>Công ty TNHH KDC</h3>
    Địa chỉ: Tầng 5 Tòa nhà Sentinel Place,<br/>
    41A Lý Thái Tổ, Hoàn Kiếm, Hà Nội.<br/>
    Tel: 04 66867668<br/>
    Email: sales@minimart.com.vn<br/>
    Website: <a href="www.minimart.com.vn">www.minimart.com.vn</a>
  </div><!--box_footer-->
  <div class="box_footer">
    <h3>Thông tin Minimart</h3>
    <ul>
      <li><a href="/page/bao-chi-viet-ve-chung-toi">Báo chí viết về chúng tôi</a> </li>
      <li><a href="/page/y-kien-khach-hang">Ý kiến khách hàng</a> </li>
      <li><a href="/tin-tuc">Tin tức</a> </li>
      <li><a href="/lien-he">Liên hệ</a> </li>
    </ul>
  </div><!--box_footer-->
  <div class="box_footer">
    <h3>Hỗ trợ khách hàng</h3>
    <ul>
      <li><a href="/page/huong-dan-chon-hang">Hướng dẫn chọn hàng</a> </li>
      <li><a href="/page/huong-dan-mua-hang">Hướng dẫn mua hàng</a> </li>
      <li><a href="/page/chinh-sach-van-chuyen">Chính sách vận chuyển</a> </li>
      <li><a href="/page/chinh-sach-doi-tra-hang">Chính sách đổi trả hàng</a> </li>
    </ul>
  </div><!--box_footer-->
  <div class="box_footer">
    <h3>Kết nối với Minimart</h3>
    <div id="social_footer">
      <a href="http://www.facebook.com/minimart.com.vn"><img src="/minimart/public/templates/default/images/icon_facebook.png" alt="Minimart.com.vn" /> </a>
      <a href=""><img src="/minimart/public/templates/default/images/icon_twitter.png" alt="Minimart.com.vn" /> </a>
      <a href=""><img src="/minimart/public/templates/default/images/icon_google.png" alt="Minimart.com.vn" /> </a>
    </div>
  </div><!--box_footer-->
  <div class="box_footer">
    <h3>Chấp nhận thanh toán</h3>
    <a href=""><img src="/minimart/public/templates/default/images/icon_pay.png" alt="" /> </a>
  </div><!--box_footer-->
</div>
<div class="clr"></div>
</div>