<div id="ddtabs1" class="basictab" style="
    float: left;
">
<ul>
<li><a class="a_tab" href="usermanagement">User Management</a></li>
<li><a class="a_tab" href="ordermanagement">Order Management</a></li>
<li><a class="a_tab" href="productmanagement">Product Management</a></li>
<li><a class="a_tab" href="categorymanagement">Category Management</a></li>
<li><a class="a_tab" href="articlemanagement">Article Management</a></li>
</ul>
</div>