
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Login</title>
<style>
    fieldset{
        width: 500px;
        border: 1px solid green;
        margin: auto;
    }
    h1{
        text-align:center;
        color: green;
    }
   #login table{
        width: 300px;
        margin: 10px auto;
   }
   legend{
        width: 100px;
        background-color: #A9D18E;
        text-align: center;
        border-radius: 0.5em;
   }
</style>
</head>
<body>
    <h1>Daily Report</h1>
    <form id="login" action="Login" method="post">
        <fieldset>
            <legend>Login</legend>
            <table>
                <tr>
                    <td width='70px' >ID</td>
                    <td>
                    <input type="text" name="user_id" id="user_id"  size="20" maxlength="150" tabindex="1"/>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                    <label id="lblUserId"></label>
                    </td>
                </tr>
                <tr>
                    <td >Password</td>
                    <td>
                        <input type="password" name="password" id="password"  size="20" maxlength="150" tabindex="1"/>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                </tr>
            </table>
            <input type="submit" name="submit" id="btnLogin" value="Login" style="margin-left: 130px;"/>
            <?php if(isset ($this -> message)) echo $this -> message;?>
        </fieldset>
           
    </form>
</body>
</html>